#!/bin/bash
echo "If external disks are mounted it will run much slower! Also eject network volumes..."
echo "Running..."
now=$(date +"%Y-%m-%d")
sudo find / -type f -size +100k ! -iwholename "/Volumes*" ! -iwholename "/dev/*" -exec wc -c {} \; > "snapshot_"$now".txt"
