#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: ./tmsnapshot DRIVE"
  exit
fi

if [ ! -d "/Volumes/${1}" ]; then
  echo "Drive ${1} is not mounted"
  exit
fi

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

find "/Volumes/${1}/Backups.backupdb/eclipse/Latest/Macintosh HD" -type f -size +100k -exec du -akx {} \; | sed "s/\/Volumes\/${1}\/Backups.backupdb\/eclipse\/Latest\/Macintosh HD//" > snapshot_prev.txt
